### ISSUE TITLE
Two waiters?

### ISSUE THREAD

**Issue by Andertius** [Slayrak/TableTracker#10]
![image](https://user-images.githubusercontent.com/48299203/152139885-6524ff8d-1b37-4cf4-8ca5-abecd57a8d92.png)

**Comment by Slayrak** [comment]
Взагалі я думаю там зробити колекцію, що типу там кілька відповідають але один обслуговує, але краще погугли або спитай у дядька)

**Comment by Slayrak** [comment]
Done
