### ISSUE TITLE
Merge Database branch into develop

### ISSUE THREAD

**Issue by Slayrak** [Slayrak/TableTracker#14]
Merge after all checkups

**Comment by Andertius** [comment]
merge into develop!!!!!!!!!!!!!!!!!!!

**Comment by Slayrak** [comment]
understandable

**Comment by Andertius** [comment]
First, merge unit of work into database

**Comment by Slayrak** [comment]
check Db unit-of-work merge

**Comment by Slayrak** [comment]
merged into develop
